### ISSUE TITLE
pointer to slides available?

### ISSUE THREAD

**Issue by flavio-fernandes** [chrisminnick/js-demos#1]
Hi @chrisminnick !

Thank you for the talk today. I am very green on js and this was a great
intro for me. Any chance we can add pointers in the readme file for the
slides/recording?

**Comment by chrisminnick** [comment]
Hi @flavio-fernandes !

I'm glad you found it useful. I've added a link to where the webinar recording will be when it's live (it's not just yet), and I'll update it when the video is posted.

-Chris
